# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXOAntsHTITacByv6nnJ9mRXp1WpMrVA
"""

import matplotlib.pyplot as plt

# Ma'lumotlar
x = [1, 2, 3, 4, 5]  # X o'qi (masalan, vaqt)
y = [2, 3, 5, 7, 11]  # Y o'qi (masalan, qiymatlar)

# Grafik chizish
plt.plot(x, y, marker='o')  # Chiziqli grafik va nuqtalar qo'shish

# Grafikga nomlar qo'shish
plt.title("Oddiy Chiziqli Grafik")
plt.xlabel("X O'qi")
plt.ylabel("Y O'qi")

# Tizimlarni ko'rsatish
plt.grid(True)  # Tizim chiziqlarini ko'rsatadi
plt.show()  # Grafikni ko'rsatish